CC=/opt/cnstools/arm-linux-le-uclibc-gcc-4.3.3-2010.05/usr/bin/arm-unknown-linux-uclibcgnueabi-gcc
AR=/opt/cnstools/arm-linux-le-uclibc-gcc-4.3.3-2010.05/usr/bin/arm-unknown-linux-uclibcgnueabi-ar
RANLIB   = /opt/cnstools/arm-linux-le-uclibc-gcc-4.3.3-2010.05/usr/bin/arm-unknown-linux-uclibcgnueabi-ranlib
PREFIX   = /home/andy/wnc/fakeroot
CFLAGS  = -O2 -Wall -Wshadow -Wredundant-decls -pipe -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE
LDFLAGS += 

